### ISSUE TITLE
JsonParseException for CouchDB for Databases with > 20k records

### ISSUE THREAD

**Issue by mittalvishesh** [cloudant/sync-android#190]
Hi

I use Cloudant Sync for Android for a few customers of mine. I am syncing databases of varying sizes to Android devices (anywhere between 5k to 500k documents with attachments).

Everything works great as long as I use Cloudant. However, as soon as I switch over to my own CouchDB installation for syncing, I get the following error:

``````
08-02 00:33:25.075   9445-18516/com.example.writingapp E/BasicPullStrategy﹕ Batch 0 ended with error:
    java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Numeric value (8580617561) out of range of int
            at [Source: java.io.InputStreamReader@424e6790; line: 1, column: 170]
            at com.cloudant.mazha.json.JSONHelper.fromJson(JSONHelper.java:58)
            at com.cloudant.mazha.CouchClient.executeToJsonObject(CouchClient.java:126)
            at com.cloudant.mazha.CouchClient.getDbInfo(CouchClient.java:148)
            at com.cloudant.sync.replication.CouchClientWrapper.exists(CouchClientWrapper.java:71)
            at com.cloudant.sync.replication.BasicPullStrategy.replicate(BasicPullStrategy.java:188)
            at com.cloudant.sync.replication.BasicPullStrategy.run(BasicPullStrategy.java:144)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (8580617561) out of range of int
            at [Source: java.io.InputStreamReader@424e6790; line: 1, column: 170]
            at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1378)
            at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:599)
            at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:835)
            at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:631)
            at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:305)
            at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:202)
            at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:187)
            at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:375)
            at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
            at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:308)
            at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
            at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2796)
            at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1965)
            at com.cloudant.mazha.json.JSONHelper.fromJson(JSONHelper.java:56)
            at com.cloudant.mazha.CouchClient.executeToJsonObject(CouchClient.java:126)
            at com.cloudant.mazha.CouchClient.getDbInfo(CouchClient.java:148)
            at com.cloudant.sync.replication.CouchClientWrapper.exists(CouchClientWrapper.java:71)
            at com.cloudant.sync.replication.BasicPullStrategy.replicate(BasicPullStrategy.java:188)
            at com.cloudant.sync.replication.BasicPullStrategy.run(BasicPullStrategy.java:144)
            at java.lang.Thread.run(Thread.java:841)
`````

This only happens with larger databases. Small databases do not show this error. Any clue?

Any help would be greatly appreciated. Thank you :)

Vish

**Comment by mittalvishesh** [comment]
Just to add on, `8580617561` is the data size.
My CouchDB installation shows the DB data in the following format:
````
{
db_name: "exampledb",
doc_count: 82297,
doc_del_count: 9885,
update_seq: 97680,
purge_seq: 0,
compact_running: false,
disk_size: 14832144521,
data_size: 8580617561,
instance_start_time: "1438201481025962",
disk_format_version: 6,
committed_update_seq: 97680
}
````

Cloudant shows the information a little differently:
````
{
update_seq: "239830-g1AAAADneJzLYWBgYMlgTmGQTUlKzi9KdUhJMtcrzsnMS9dLzskvTUnMK9HLSy3JASpjSmRIsv___39WEgPDa2ki9SQ5AMmkeqi2d7yo2sxwactjAZIMDUAKqHM_SOvzyahaTfFrPQDRCrb1hXQWAC9dTP0",
db_name: "exampledb",
sizes: {
file: 8794661756,
external: 8651339913,
active: 8679901747
},
purge_seq: 0,
other: {
data_size: 8651339913
},
doc_del_count: 9885,
doc_count: 82297,
disk_size: 8794661756,
disk_format_version: 6,
compact_running: false,
instance_start_time: "0"
}
````

**Comment by rhyshort** [comment]
fixed in https://github.com/cloudant/sync-android/commit/e151e81d35fdbd2adc7c51f418ea1e4c590a5a29
