### ISSUE TITLE
Query Conflict

### ISSUE THREAD

**Issue by segunmicheal27** [cloudant/sync-android#242]
I encounter this error when i call this code: ```
IndexManager indexManager = new IndexManager(ds);
        indexManager.ensureIndexed(Arrays.<Object>asList("name", "age"), "default");

```
```
E/SQLiteLog: (1) table _t_cloudant_sync_query_index_default already exists
03-13 13:26:19.934 23254-23254/com.example.hello.coudapp E/IndexCreator: Execution error encountered:
                                                                                 java.util.concurrent.ExecutionException: android.database.sqlite.SQLiteException: table _t_cloudant_sync_query_index_default already exists (code 1): , while compiling: CREATE TABLE _t_cloudant_sync_query_index_default ( "_id" NONE,"_rev" NONE,"name" NONE,"age" NONE )
                                                                                     at java.util.concurrent.FutureTask.report(FutureTask.java:94)
                                                                                     at 
```java.util.concurrent.FutureTask.get(FutureTask.java:164)
                                                                                     at com.cloudant.sync.query.IndexCreator.ensureIndexed(IndexCreator.java:213)
                                                                                     at com.cloudant.sync.query.IndexCreator.ensureIndexed(IndexCreator.java:57)
                                                                                     at com.cloudant.sync.query.IndexManager.ensureIndexed(IndexManager.java:242)
                                                                                     at com.example.michaelwizard.coudapp.MainActivity.setFindQuery2(MainActivity.java:131)
                                                                                     at com.example.michaelwizard.coudapp.MainActivity.findDocument(MainActivity.java:238)
                                                                                     at com.example.michaelwizard.coudapp.MainActivity.onClick(MainActivity.java:175)
                                                                                     at android.view.View.performClick(View.java:5198)
                                                                                     at android.view.View$PerformClick.run(View.java:21147)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                  Caused by: android.database.sqlite.SQLiteException: table _t_cloudant_sync_query_index_default already exists (code 1): , while compiling: CREATE TABLE _t_cloudant_sync_query_index_default ( "_id" NONE,"_rev" NONE,"name" NONE,"age" NONE )
                                                                                     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                                     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                                     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                     at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                                     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
                                                                                     at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
                                                                                     at com.cloudant.sync.sqlite.android.AndroidSQLite.execSQL(AndroidSQLite.java:84)
                                                                                     at com.cloudant.sync.query.IndexCreator$1.call(IndexCreator.java:192)
                                                                                     at com.cloudant.sync.query.IndexCreator$1.call(IndexCreator.java:146)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by tomblench** [comment]
@segunmicheal27 can you share with us the code which causes this exception? If you could upload this as a gist or similar we would be grateful.

**Comment by segunmicheal27** [comment]
```
File path = getApplicationContext().getDir("data", MainActivity.MODE_PRIVATE);
        DatastoreManager manager = new DatastoreManager(path.getAbsolutePath());
        URI uri = new URI("https://xxx-xxx-xxxx-xxxx-xxxx-bluemix:xxxxxxxxxxxxxx@xxxx-xxx-xxxxx-xx-xxxx-bluemix.cloudant.com/yourdatabase");
        Datastore ds = manager.openDatastore("mynewdatastores");
// Replicate from the local to remote database
        // Create a replicator that replicates changes from the remote
// database to the local datastore.

        Replicator replicator = ReplicatorBuilder.pull().from(uri).to(ds).build();

// Create a sample index on type field
        IndexManager indexManager = new IndexManager(ds);
        // Create an index over the name, age fields.
        indexManager.ensureIndexed(Arrays.<Object>asList("field name", "field column"), "index name", "index type"); //error occur here
        Map<String, Object> query = new HashMap<>();
        query.put("name", "anyname");
//        query.put("age", 3400);
        QueryResult result = indexManager.find(query);

        for (DocumentRevision revision : result) {            
            // do something
System.out.println("Body result"+revision.getbody);  //i get to print all my result body here          
            }
```

**Comment by tomblench** [comment]
@segunmicheal27 just use the two-arg version of `ensureIndexed`:
```java
indexManager.ensureIndexed(Arrays.<Object>asList("field name", "field column"), "index_name");
```
This assumes that you have top-level json keys named `field name` and `field column` which you wish to index.

Note that there is an undocumented bug meaning that you cannot use certain characters such as spaces in index names, hence my suggestion of `index_name`.

**Comment by tomblench** [comment]
@segunmicheal27 as a follow-up, looking at your code it is more likely that you will want to index the `name` and `age` fields:
```java
indexManager.ensureIndexed(Arrays.<Object>asList("name", "age"), "my_index");
```
