### ISSUE TITLE
IndexManager: documentation does not mention if/when to close it

### ISSUE THREAD

**Issue by mtotschnig** [cloudant/sync-android#301]
When IndexManager is used as described in the wiki, i.e. without calling explicitly close on it, the following violation to strict mode is raised, when ensureIndex is called the first time:
```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                   java.lang.Throwable: Explicit termination method 'close' not called
                                                                       at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:807)
                                                                       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
                                                                       at com.cloudant.sync.sqlite.android.AndroidSQLite.createAndroidSQLite(AndroidSQLite.java:37)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.cloudant.sync.sqlite.SQLDatabaseFactory.openSqlDatabase(SQLDatabaseFactory.java:118)
                                                                       at com.cloudant.sync.query.IndexManager$1.call(IndexManager.java:111)
                                                                       at com.cloudant.sync.query.IndexManager$1.call(IndexManager.java:108)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
```
This does not happen, if close is called after retrieving the query result
I am not sure if this is a documentation bug (mention missing that close needs to be called for IndexManager) or if this would need to be solved differently?

**Comment by rhyshort** [comment]
Sounds like a documentation issue, you should call `close` on the index manager when you are finished with it. Do you have the location of the example that doesn't call `close`?

**Comment by mtotschnig** [comment]
I am referring to https://github.com/cloudant/sync-android/blob/master/doc/query.md

**Comment by rhyshort** [comment]
Thanks, I'll take a look
