### ISSUE TITLE
Intermittent AttachmentsPullTest failure

### ISSUE THREAD

**Issue by ricellis** [cloudant/sync-android#360]
This looks different from the issues previously seen in #337, but may be related. The "Socket closed" looks like we're trying to use something already closed (internally I think we would get a broken pipe if it was closed at the server).

>com.cloudant.sync.replication.AttachmentsPullTest > dontPullAttachmentAlreadyPulled[0] FAILED
    java.lang.AssertionError: Create/pull error java.lang.RuntimeException:
java.net.SocketException: Socket closed
        at org.junit.Assert.fail(Assert.java:88)
        at com.cloudant.sync.replication.AttachmentsPullTest.dontPullAttachmentAlreadyPulled(AttachmentsPullTest.java:198)

**Comment by ricellis** [comment]
Saw yet another failure mode with this test:

>com.cloudant.sync.replication.AttachmentsPullTest > dontPullAttachmentAlreadyPulled[0] FAILED

>CouchException: error: file_exists, reason: The database could not be created, the file already exists., statusCode: 412, msg: Precondition Failed, cause: java.io.IOException: Server returned HTTP response code: 412 for URL: http://127.0.0.1:5984/attachments_pull_test1476725683802

>Caused by: java.io.IOException: Server returned HTTP response code: 412 for URL: http://127.0.0.1:5984/attachments_pull_test1476725683802
