### ISSUE TITLE
Cloudant bulkCreateDocs error

### ISSUE THREAD

**Issue by defaultbr** [cloudant/sync-android#516]
```
03-17 19:43:51.233 17456-19371/oi.oi E/CouchClientWrapper: Unknown bulkCreateDocs API error: [{id=1cce93b18df34f7f9ece6fe4fb46633c, rev=1-d36b53f8846e463187e70ec03da46a89, error=forbidden, reason=The `source' property must exist and be either a string or an object.}] for input: [{"_rev":"1-d36b53f8846e463187e70ec03da46a89","checkFaceAccuracy":0.0,"checkFakeGps":false,"name":"hhdhdhdhduid","enabled":false,"_revisions":{"start":1,"ids":["d36b53f8846e463187e70ec03da46a89"]},"doc_type":"Device","_id":"1cce93b18df34f7f9ece6fe4fb46633c","insecureMode":false,"checkFace":false,"selectedCompaniesOid":["575ebbc8a098db682097930e","589b7f370c28e68a99d7376a","58751d466ba5c26e0f97b998","575eb6d3a098db6820979303","57ebe42e961df8600ad1313a","5846fa296ba5c26e0f968f18"]}]
03-17 19:43:51.235 17456-19371/oi.oi E/PushStrategy: Batch 1 ended with error:
                                                              java.lang.RuntimeException: Unknown bulkCreateDocs api error
                                                                  at com.cloudant.sync.internal.replication.CouchClientWrapper.bulkCreateSerializedDocs(CouchClientWrapper.java:247)
                                                                  at com.cloudant.sync.internal.replication.PushStrategy.processOneChangesBatch(PushStrategy.java:353)
                                                                  at com.cloudant.sync.internal.replication.PushStrategy.replicate(PushStrategy.java:252)
                                                                  at com.cloudant.sync.internal.replication.PushStrategy.run(PushStrategy.java:165)
                                                                  at java.lang.Thread.run(Thread.java:761)
```

im creating the DocumentRevision (or its updated) and after that, the push is not working

**Comment by defaultbr** [comment]
found solution: http://stackoverflow.com/a/41653082/7564126


i removed the _replicator document from the database, and it started working again
